import path from 'node:path';
import { coverageConfigDefaults, defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // virtual:pwa-register/react is generated by vite-plugin-pwa at build
      // time; it does not exist on disk.  Map it to a stub so unit tests can
      // import UpdatePrompt.tsx (tests that need specific behaviour should
      // vi.mock('virtual:pwa-register/react') on top of this stub).
      'virtual:pwa-register/react': path.resolve(
        __dirname,
        './src/test/stubs/pwa-register-react.ts',
      ),
    },
  },
  test: {
    clearMocks: true,
    css: true,
    environment: 'jsdom',
    // Half the cores, not all of them: with one jsdom worker per core the
    // pool oversubscribes the box (cumulative import time ~4x wall time) and
    // starved workers miss Testing Library's async windows, flaking tests
    // that pass in isolation.
    maxWorkers: '50%',
    globals: false,
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    restoreMocks: true,
    setupFiles: ['./src/test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'json', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      // Keep Vitest's defaults (test files, *.d.ts, configs) and also exclude
      // the shared test harness under src/test/.
      exclude: [...coverageConfigDefaults.exclude, 'src/test/**'],
      // Ratchet floor: these are the measured whole-src baselines at the time
      // this gate was added (see PR), floored to whole numbers. Raise them as
      // coverage grows; never lower them to make a PR pass.
      thresholds: {
        statements: 14,
        branches: 8,
        functions: 9,
        lines: 15,
      },
    },
  },
});
