import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { dashboardPdfFixture } from './fixtures';
import { JsPdfRecorder, latestPdf, renderedText } from './pdfTestRecorder';
import { generateDashboardPDF } from '../../pdfGenerator';
import type { DashboardPDFData } from '../../pdfGenerator';

vi.mock('jspdf', () => ({
  jsPDF: JsPdfRecorder,
}));

describe('dashboard PDF characterization', () => {
  beforeEach(() => {
    JsPdfRecorder.instances = [];
    vi.setSystemTime(new Date('2026-05-28T02:00:00.000Z'));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('preserves dashboard summary PDF headings, metrics, and filename', async () => {
    await generateDashboardPDF(dashboardPdfFixture);

    const doc = latestPdf();
    const text = renderedText(doc);

    expect(doc.constructorArgs).toEqual(['portrait', 'mm', 'a4']);
    expect(doc.savedFilename).toBe('Dashboard-Summary-2026-05-28.pdf');
    expect(text).toEqual(
      expect.arrayContaining([
        'Dashboard Summary',
        'Report Details',
        'Date range',
        'Last 30 days',
        'Exported by',
        'Pat Owner',
        'Key Metrics',
        'Total projects',
        '3',
        'Active projects',
        '2',
        'Total lots',
        '18',
        'Open hold points',
        '4',
        'Open NCRs',
        '1',
        'Attention items',
        'Overdue NCRs',
        '1. NCR-0007 pavement thickness (PHU-001 - Pacific Highway Upgrade)',
        '5 days overdue. Corrective action overdue for pavement lot.',
        'Stale Hold Points',
        '1. Release concrete pour hold point (PHU-001 - Pacific Highway Upgrade)',
        '3 days waiting. Awaiting client release before pour.',
        'Recent Activity',
        '1. Lot EW-001 changed to conformed',
      ]),
    );
    // Customer brand owns the header; the platform identifies itself only in
    // the shared per-page footer attribution.
    expect(text.join('\n')).not.toContain('CIVOS Civil Execution and Conformance Platform');
    expect(text).toContain('Generated by CIVOS · civos.com.au');
    expect(text.join('\n')).not.toContain('SiteProof v2');
  });

  it('renders dashboard fallback copy when attention and activity sections are empty', async () => {
    const dashboardFixtureWithEmptySections: DashboardPDFData = {
      ...dashboardPdfFixture,
      stats: {
        ...dashboardPdfFixture.stats,
        attentionItems: { total: 0, overdueNCRs: [], staleHoldPoints: [] },
        recentActivities: [],
      },
    };

    await generateDashboardPDF(dashboardFixtureWithEmptySections);

    const doc = latestPdf();
    const text = renderedText(doc);

    expect(doc.constructorArgs).toEqual(['portrait', 'mm', 'a4']);
    expect(text).toEqual(
      expect.arrayContaining([
        'Overdue NCRs',
        'Stale Hold Points',
        'Recent Activity',
        'None',
        'No recent activity in this period.',
      ]),
    );
  });
});
