import type {
  ClaimEvidencePackageData,
  DashboardPDFData,
  DailyDiaryPDFData,
  DocketDetailPDFData,
  HPEvidencePackageData,
  NCRDetailData,
  TestCertificateData,
} from '../../pdfGenerator';

export const dashboardPdfFixture: DashboardPDFData = {
  generatedAt: '2026-05-28T03:15:00.000Z',
  exportedBy: 'Pat Owner',
  dateRange: {
    label: 'Last 30 days',
    startDate: '2026-05-01',
    endDate: '2026-05-28',
  },
  stats: {
    totalProjects: 3,
    activeProjects: 2,
    totalLots: 18,
    openHoldPoints: 4,
    openNCRs: 1,
    attentionItems: {
      total: 2,
      overdueNCRs: [
        {
          id: 'ncr-1',
          type: 'ncr',
          title: 'NCR-0007 pavement thickness',
          description: 'Corrective action overdue for pavement lot.',
          status: 'open',
          daysOverdue: 5,
          project: {
            id: 'project-1',
            name: 'Pacific Highway Upgrade',
            projectNumber: 'PHU-001',
          },
        },
      ],
      staleHoldPoints: [
        {
          id: 'hp-1',
          type: 'holdpoint',
          title: 'Release concrete pour hold point',
          description: 'Awaiting client release before pour.',
          status: 'requested',
          daysStale: 3,
          project: {
            id: 'project-1',
            name: 'Pacific Highway Upgrade',
            projectNumber: 'PHU-001',
          },
        },
      ],
    },
    recentActivities: [
      {
        id: 'activity-1',
        type: 'lot_status_changed',
        description: 'Lot EW-001 changed to conformed',
        timestamp: '2026-05-27T22:00:00.000Z',
      },
    ],
  },
};

export const passingTestCertificateFixture: TestCertificateData = {
  test: {
    id: 'test-result-1',
    testType: 'Compaction',
    testRequestNumber: 'TR-001',
    laboratoryName: 'Civil Lab Australia',
    laboratoryReportNumber: 'LAB-9931',
    sampleDate: '2026-05-20T00:00:00.000Z',
    sampleLocation: 'CH 100-120 LHS',
    testDate: '2026-05-21T00:00:00.000Z',
    resultDate: '2026-05-22T00:00:00.000Z',
    resultValue: 98,
    resultUnit: '%',
    specificationMin: 95,
    specificationMax: 100,
    passFail: 'pass',
    status: 'verified',
    aiExtracted: true,
    createdAt: '2026-05-22T04:30:00.000Z',
  },
  lot: {
    lotNumber: 'EW-001',
    description: 'Earthworks test section',
    activityType: 'Earthworks',
    chainageStart: 100,
    chainageEnd: 120,
  },
  project: {
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
  },
};

export const majorNcrDetailFixture: NCRDetailData = {
  ncr: {
    ncrNumber: 'NCR-0009',
    description: 'Honeycombing identified on headwall concrete face after formwork strip.',
    category: 'workmanship',
    severity: 'major',
    status: 'pending_review',
    rootCause: 'Insufficient vibration around congested reinforcement.',
    proposedAction: 'Break out defective concrete and reinstate with approved repair mortar.',
    actionTaken: 'Repair methodology submitted for superintendent review.',
    preventativeMeasures: 'Brief crew on vibration pattern and add pre-pour checklist hold point.',
    lessonsLearned: 'Increase inspection frequency when reinforcement congestion is high.',
    qmApprovalRequired: true,
    qmApprovedAt: null,
    qmApprovedBy: null,
    raisedBy: {
      fullName: 'Quinn Manager',
      email: 'quinn@example.com',
    },
    responsibleUser: {
      fullName: 'Sam Supervisor',
      email: 'sam@example.com',
    },
    dueDate: '2026-06-04T00:00:00.000Z',
    closedAt: null,
    closedBy: null,
    createdAt: '2026-05-28T01:30:00.000Z',
  },
  project: {
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
  },
  lots: [
    {
      lotNumber: 'STR-042',
      description: 'Headwall concrete repair',
    },
  ],
  timeline: [
    {
      action: 'NCR raised',
      performedBy: 'Quinn Manager',
      performedAt: '2026-05-28T01:30:00.000Z',
      notes: 'Photos attached in document register.',
    },
  ],
};

export const approvedDocketDetailFixture: DocketDetailPDFData = {
  docket: {
    id: 'docket-1',
    docketNumber: 'SD-0042',
    date: '2026-05-28T12:00:00.000Z',
    status: 'approved',
    notes: 'Completed drainage trenching and bedding placement for eastern run.',
    labourHours: 42,
    plantHours: 12,
    totalLabourSubmitted: 42,
    totalLabourApproved: 40,
    totalPlantSubmitted: 12,
    totalPlantApproved: 13,
    submittedAt: '2026-05-28T05:30:00.000Z',
    approvedAt: '2026-05-28T07:45:00.000Z',
    foremanNotes: 'Reduced labour by two hours after duplicate spotter entry was removed.',
    rejectionReason: null,
    adjustmentReason: 'Plant time increased for excavator standby during services potholing.',
  },
  subcontractor: {
    name: 'Precision Drainage Pty Ltd',
    abn: '12 345 678 901',
  },
  project: {
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
  },
};

export const submittedDailyDiaryFixture: DailyDiaryPDFData = {
  diary: {
    id: 'diary-1',
    date: '2026-05-28T12:00:00.000Z',
    status: 'submitted',
    weatherConditions: 'Cloudy with light rain',
    temperatureMin: 14,
    temperatureMax: 22,
    rainfallMm: 6,
    weatherNotes: 'Light rain paused excavation around lunch.',
    generalNotes:
      '<p>Morning toolbox completed before crews opened drainage trench.</p><p>Inspection photos uploaded.</p>',
    isLate: true,
    submittedBy: {
      fullName: 'Riley Foreman',
      email: 'riley@example.com',
    },
    submittedAt: '2026-05-28T08:30:00.000Z',
    createdAt: '2026-05-28T00:30:00.000Z',
    updatedAt: '2026-05-28T08:30:00.000Z',
  },
  project: {
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
  },
  personnel: [
    {
      id: 'person-1',
      name: 'Nina Foreman',
      company: 'SiteProof Civil',
      role: 'Foreman',
      startTime: '06:30',
      finishTime: '15:00',
      hours: 8.5,
    },
    {
      id: 'person-2',
      name: 'Drainage Crew A',
      company: 'Drainage Crew',
      role: 'Pipe layer',
      startTime: '07:00',
      finishTime: '14:30',
      hours: 7.5,
    },
  ],
  plant: [
    {
      id: 'plant-1',
      description: 'Excavator 20t',
      idRego: 'EX-204',
      company: 'Drainage Crew',
      hoursOperated: 7,
      notes: 'Trimmed trench invert',
    },
  ],
  activities: [
    {
      id: 'activity-1',
      description: 'Drainage trench excavation',
      lot: { lotNumber: 'DR-010' },
      quantity: 24,
      unit: 'm',
      notes: 'Reached inspection hold point',
    },
  ],
  delays: [
    {
      id: 'delay-1',
      delayType: 'Weather',
      description: 'Short rain delay during bedding',
      startTime: '11:15',
      endTime: '12:00',
      durationHours: 0.75,
      impact: 'Delayed bedding compaction',
    },
  ],
  addendums: [
    {
      id: 'addendum-1',
      content: 'Client requested photo set attached after inspection.',
      addedBy: {
        fullName: 'Riley Reviewer',
        email: 'reviewer@example.com',
      },
      addedAt: '2026-05-28T09:10:00.000Z',
    },
  ],
};

export const submittedClaimEvidencePackageFixture: ClaimEvidencePackageData = {
  claim: {
    id: 'claim-1',
    claimNumber: 7,
    periodStart: '2026-05-01T00:00:00.000Z',
    periodEnd: '2026-05-28T00:00:00.000Z',
    status: 'submitted',
    totalClaimedAmount: 248500,
    certifiedAmount: null,
    submittedAt: '2026-05-29T01:00:00.000Z',
    preparedBy: {
      name: 'Morgan Estimator',
      email: 'morgan@example.com',
    },
    preparedAt: '2026-05-29T00:30:00.000Z',
  },
  project: {
    id: 'project-1',
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
    clientName: 'Transport for NSW',
    state: 'NSW',
  },
  lots: [
    {
      id: 'lot-1',
      lotNumber: 'EW-001',
      description: 'Bulk earthworks to subgrade level',
      activityType: 'Earthworks',
      chainageStart: 100,
      chainageEnd: 350,
      layer: 'Subgrade',
      areaZone: 'Zone A',
      status: 'conformed',
      conformedAt: '2026-05-20T05:00:00.000Z',
      conformedBy: {
        name: 'Jordan Surveyor',
        email: 'jordan@example.com',
      },
      claimAmount: 185000,
      percentComplete: 100,
      itp: {
        templateName: 'Earthworks ITP - Subgrade',
        checklistItems: [{}, {}, {}, {}],
        completions: [
          { isCompleted: true },
          { isCompleted: true },
          { isCompleted: true },
          { isCompleted: true },
        ],
        holdPoints: [{ status: 'released' }, { status: 'released' }],
      },
      testResults: [
        { testType: 'Compaction', resultValue: 98, resultUnit: '%', passFail: 'pass' },
        { testType: 'Moisture', resultValue: 12, resultUnit: '%', passFail: 'pass' },
        { testType: 'CBR', resultValue: 45, resultUnit: '%', passFail: 'pass' },
      ],
      ncrs: [],
      documents: [],
      summary: {
        testResultCount: 3,
        passedTestCount: 3,
        ncrCount: 0,
        openNcrCount: 0,
        photoCount: 6,
        itpCompletionPercentage: 100,
      },
    },
    {
      id: 'lot-2',
      lotNumber: 'DR-014',
      description: 'Stormwater drainage line and pits',
      activityType: 'Drainage',
      chainageStart: 200,
      chainageEnd: 260,
      layer: null,
      areaZone: 'Zone B',
      status: 'in_progress',
      conformedAt: null,
      conformedBy: null,
      claimAmount: 63500,
      percentComplete: 75,
      itp: {
        templateName: 'Drainage ITP - Pipe Laying',
        checklistItems: [{}, {}, {}, {}],
        completions: [
          { isCompleted: true },
          { isCompleted: true },
          { isCompleted: true },
          { isCompleted: false },
        ],
        holdPoints: [{ status: 'released' }, { status: 'pending' }],
      },
      testResults: [
        { testType: 'Concrete Slump', resultValue: 80, resultUnit: 'mm', passFail: 'pass' },
        { testType: 'Pipe Joint', resultValue: null, resultUnit: null, passFail: 'fail' },
      ],
      ncrs: [{ ncrNumber: 'NCR-0021', severity: 'minor', status: 'open' }],
      documents: [],
      summary: {
        testResultCount: 2,
        passedTestCount: 1,
        ncrCount: 1,
        openNcrCount: 1,
        photoCount: 3,
        itpCompletionPercentage: 75,
      },
    },
  ],
  summary: {
    totalLots: 2,
    totalClaimedAmount: 248500,
    totalTestResults: 5,
    totalPassedTests: 4,
    totalNCRs: 1,
    totalOpenNCRs: 1,
    totalPhotos: 9,
    conformedLots: 1,
  },
  generatedAt: '2026-05-28T03:15:00.000Z',
  generationTimeMs: 1234,
};

// Released hold point with every optional section populated (checklist rows,
// test-result table, photo list, release details, survey chainage).
export const releasedHpEvidencePackageFixture: HPEvidencePackageData = {
  holdPoint: {
    id: 'hp-1',
    description: 'Subgrade proof roll prior to pavement layer',
    status: 'released',
    notificationSentAt: '2026-05-26T22:00:00.000Z',
    scheduledDate: '2026-05-27T00:00:00.000Z',
    releasedAt: '2026-05-27T06:30:00.000Z',
    releasedByName: 'Sam Supervisor',
    releaseNotes: 'Released after surveyor confirmed level tolerance.',
  },
  lot: {
    id: 'lot-1',
    lotNumber: 'EW-001',
    description: 'Bulk earthworks to subgrade level',
    activityType: 'Earthworks',
    chainageStart: 100,
    chainageEnd: 350,
  },
  project: {
    id: 'project-1',
    name: 'Pacific Highway Upgrade',
    projectNumber: 'PHU-001',
  },
  itpTemplate: {
    id: 'itp-1',
    name: 'Earthworks ITP - Subgrade',
    activityType: 'Earthworks',
  },
  checklist: [
    {
      sequenceNumber: 1,
      description: 'Confirm survey set-out',
      pointType: 'standard',
      responsibleParty: 'Surveyor',
      isCompleted: true,
      completedAt: '2026-05-27T01:00:00.000Z',
      completedBy: 'Jordan Surveyor',
      isVerified: true,
      verifiedAt: '2026-05-27T02:00:00.000Z',
      verifiedBy: 'Sam Supervisor',
      notes: null,
      attachments: [],
    },
    {
      sequenceNumber: 2,
      description: 'Proof roll subgrade',
      pointType: 'hold_point',
      responsibleParty: 'Foreman',
      isCompleted: true,
      completedAt: '2026-05-27T03:00:00.000Z',
      completedBy: 'Riley Foreman',
      isVerified: false,
      verifiedAt: null,
      verifiedBy: null,
      notes: null,
      attachments: [
        {
          id: 'attach-1',
          filename: 'proof-roll.jpg',
          fileUrl: null,
          caption: null,
        },
      ],
    },
    {
      sequenceNumber: 3,
      description: 'Witness density testing',
      pointType: 'witness',
      responsibleParty: 'Engineer',
      isCompleted: false,
      completedAt: null,
      completedBy: null,
      isVerified: false,
      verifiedAt: null,
      verifiedBy: null,
      notes: null,
      attachments: [],
    },
  ],
  testResults: [
    {
      id: 'tr-1',
      testType: 'Compaction',
      testRequestNumber: 'TR-001',
      laboratoryName: 'Civil Lab',
      resultValue: 98,
      resultUnit: '%',
      passFail: 'pass',
      status: 'verified',
      isVerified: true,
      verifiedBy: 'Sam Supervisor',
      createdAt: '2026-05-27T04:00:00.000Z',
    },
    {
      id: 'tr-2',
      testType: 'Moisture',
      testRequestNumber: 'TR-002',
      laboratoryName: 'Civil Lab',
      resultValue: 12,
      resultUnit: '%',
      passFail: 'fail',
      status: 'submitted',
      isVerified: false,
      verifiedBy: null,
      createdAt: '2026-05-27T04:30:00.000Z',
    },
  ],
  photos: [
    {
      id: 'photo-1',
      filename: 'subgrade-east.jpg',
      fileUrl: null,
      caption: 'East end after proof roll',
      uploadedAt: '2026-05-27T05:00:00.000Z',
    },
    {
      id: 'photo-2',
      filename: 'level-check.jpg',
      fileUrl: null,
      caption: null,
      uploadedAt: null,
    },
  ],
  summary: {
    totalChecklistItems: 3,
    completedItems: 2,
    verifiedItems: 1,
    totalTestResults: 2,
    passingTests: 1,
    totalPhotos: 2,
    totalAttachments: 1,
  },
  generatedAt: '2026-05-28T03:15:00.000Z',
};

// Not-yet-released hold point with all optional sections empty/absent
// (no release details, no checklist rows, no test results, no photos,
// no project number, no lot description/activity/chainage).
export const notifiedHpEvidencePackageFixture: HPEvidencePackageData = {
  holdPoint: {
    id: 'hp-2',
    description: 'Concrete pour hold point awaiting release',
    status: 'notified',
    notificationSentAt: '2026-05-27T22:00:00.000Z',
    scheduledDate: null,
    releasedAt: null,
    releasedByName: null,
    releaseNotes: null,
  },
  lot: {
    id: 'lot-2',
    lotNumber: 'STR-101',
    description: null,
    activityType: null,
    chainageStart: null,
    chainageEnd: null,
  },
  project: {
    id: 'project-2',
    name: 'Pacific Highway Upgrade',
    projectNumber: null,
  },
  itpTemplate: {
    id: 'itp-2',
    name: 'Structures ITP - Headwall',
    activityType: null,
  },
  checklist: [],
  testResults: [],
  photos: [],
  summary: {
    totalChecklistItems: 0,
    completedItems: 0,
    verifiedItems: 0,
    totalTestResults: 0,
    passingTests: 0,
    totalPhotos: 0,
    totalAttachments: 0,
  },
  generatedAt: '2026-05-28T03:15:00.000Z',
};
