import { describe, expect, it } from 'vitest';
import {
  buildTestRequestFormMetadata,
  buildTestRequestFormResponse,
  buildVerificationViewData,
  buildVerificationViewResponse,
  escapeHtml,
  renderTestRequestFormHtml,
  type RequestFormSource,
  type VerificationViewSource,
} from './presentation.js';

const requestFormSource = (overrides: Partial<RequestFormSource> = {}): RequestFormSource => ({
  id: 'abcdef1234567890',
  testRequestNumber: 'TRN-7',
  testType: 'Compaction Test',
  laboratoryName: 'ACME Labs',
  sampleDate: null,
  sampleLocation: 'CH 1200 RHS',
  resultUnit: '% MDD',
  specificationMin: 95,
  specificationMax: 100,
  createdAt: new Date('2026-05-15T02:00:00.000Z'),
  project: {
    name: 'Northern Bypass',
    projectNumber: 'PN-001',
    clientName: 'DIT',
    company: { name: 'Ryox Carpentry', abn: '12 345 678 901', address: '1 Site Rd' },
  },
  lot: {
    lotNumber: 'LOT-12',
    description: 'Subgrade prep',
    chainageStart: 1200,
    chainageEnd: 1300,
    layer: 'Subgrade',
    activityType: 'earthworks',
  },
  enteredBy: { fullName: 'Jane Foreman', email: 'jane@example.com', phone: '0400000000' },
  ...overrides,
});

const verificationViewSource = (
  overrides: Partial<VerificationViewSource> = {},
): VerificationViewSource => ({
  id: 'tr-1',
  testType: 'Compaction Test',
  testRequestNumber: 'TRN-7',
  laboratoryName: 'ACME Labs',
  laboratoryReportNumber: 'LR-9',
  sampleDate: null,
  sampleLocation: 'CH 1200 RHS',
  testDate: null,
  resultDate: null,
  resultValue: 98,
  resultUnit: '% MDD',
  specificationMin: 95,
  specificationMax: 100,
  passFail: 'pass',
  status: 'entered',
  aiExtracted: false,
  aiConfidence: null,
  enteredAt: null,
  verifiedAt: null,
  createdAt: new Date('2026-05-15T02:00:00.000Z'),
  updatedAt: new Date('2026-05-16T02:00:00.000Z'),
  project: { id: 'p1', name: 'Northern Bypass', projectNumber: 'PN-001', specificationSet: 'TMR' },
  lot: {
    id: 'l1',
    lotNumber: 'LOT-12',
    description: 'Subgrade prep',
    activityType: 'earthworks',
    chainageStart: 1200,
    chainageEnd: 1300,
    layer: 'Subgrade',
  },
  enteredBy: { id: 'u1', fullName: 'Jane Foreman', email: 'jane@example.com' },
  verifiedBy: null,
  certificateDoc: null,
  ...overrides,
});

describe('escapeHtml', () => {
  it('escapes HTML-sensitive characters', () => {
    expect(escapeHtml(`A & B <Co> "x" 'y'`)).toBe('A &amp; B &lt;Co&gt; &quot;x&quot; &#39;y&#39;');
  });

  it('returns the fallback for null, undefined, and empty string', () => {
    expect(escapeHtml(null)).toBe('N/A');
    expect(escapeHtml(undefined)).toBe('N/A');
    expect(escapeHtml('')).toBe('N/A');
    expect(escapeHtml(null, '')).toBe('');
    expect(escapeHtml('', '(none)')).toBe('(none)');
  });

  it('stringifies non-empty non-string values (including 0)', () => {
    expect(escapeHtml(0)).toBe('0');
    expect(escapeHtml(123)).toBe('123');
  });
});

describe('renderTestRequestFormHtml', () => {
  it('renders the printable form scaffold and key headings', () => {
    const html = renderTestRequestFormHtml(requestFormSource());
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<h1>TEST REQUEST FORM</h1>');
    expect(html).toContain('Project Information');
    expect(html).toContain('Sample Location');
    expect(html).toContain('Test Details');
    expect(html).toContain('Specification Requirements');
    expect(html).toContain('Notes / Special Instructions');
    expect(html).toContain('Generated by SiteProof |');
  });

  it('renders project, company, and sample values into the form', () => {
    const html = renderTestRequestFormHtml(requestFormSource());
    expect(html).toContain('Northern Bypass');
    expect(html).toContain('PN-001');
    expect(html).toContain('DIT');
    expect(html).toContain('Ryox Carpentry');
    expect(html).toContain('ABN: 12 345 678 901');
    expect(html).toContain('LOT-12');
    expect(html).toContain('ACME Labs');
    // specificationValue appends the result unit
    expect(html).toContain('95 % MDD');
    expect(html).toContain('100 % MDD');
  });

  it('falls back to a TRF- request number derived from the id when none is set', () => {
    const html = renderTestRequestFormHtml(requestFormSource({ testRequestNumber: null }));
    expect(html).toContain('TRF-ABCDEF12');
  });

  it('falls back to "Company" when the company name is missing', () => {
    const html = renderTestRequestFormHtml(
      requestFormSource({
        project: { name: 'P', projectNumber: null, clientName: null, company: null },
      }),
    );
    expect(html).toContain('<div class="company-name">Company</div>');
  });

  it('escapes HTML-sensitive values in the rendered form', () => {
    const html = renderTestRequestFormHtml(
      requestFormSource({ laboratoryName: `A & B <Co> "x" 'y'` }),
    );
    expect(html).toContain('A &amp; B &lt;Co&gt; &quot;x&quot; &#39;y&#39;');
    expect(html).not.toContain('<Co>');
  });
});

describe('buildTestRequestFormMetadata', () => {
  it('builds the JSON metadata shape from the source', () => {
    const createdAt = new Date('2026-05-15T02:00:00.000Z');
    expect(buildTestRequestFormMetadata(requestFormSource({ createdAt }))).toEqual({
      requestNumber: 'TRN-7',
      project: {
        name: 'Northern Bypass',
        number: 'PN-001',
        client: 'DIT',
        company: 'Ryox Carpentry',
      },
      lot: {
        number: 'LOT-12',
        description: 'Subgrade prep',
        activityType: 'earthworks',
        chainageStart: 1200,
        chainageEnd: 1300,
        layer: 'Subgrade',
      },
      testDetails: {
        type: 'Compaction Test',
        laboratory: 'ACME Labs',
        sampleDate: null,
        sampleLocation: 'CH 1200 RHS',
      },
      specifications: { min: 95, max: 100, unit: '% MDD' },
      requestedBy: { fullName: 'Jane Foreman', email: 'jane@example.com', phone: '0400000000' },
      createdAt,
    });
  });

  it('derives the TRF- request number and null lot when absent', () => {
    const metadata = buildTestRequestFormMetadata(
      requestFormSource({ testRequestNumber: null, lot: null }),
    );
    expect(metadata.requestNumber).toBe('TRF-ABCDEF12');
    expect(metadata.lot).toBeNull();
  });
});

describe('buildVerificationViewData', () => {
  it('computes pass / fail / unknown specification status', () => {
    const status = (overrides: Partial<VerificationViewSource>) =>
      buildVerificationViewData(verificationViewSource(overrides), { canVerify: false })
        .specification.calculatedStatus;

    expect(status({ resultValue: 98, specificationMin: 95, specificationMax: 100 })).toBe('pass');
    expect(status({ resultValue: 120, specificationMin: 95, specificationMax: 100 })).toBe('fail');
    expect(status({ resultValue: null })).toBe('unknown');
    expect(status({ resultValue: 90, specificationMin: 95, specificationMax: null })).toBe('fail');
    expect(status({ resultValue: 99, specificationMin: 95, specificationMax: null })).toBe('pass');
    expect(status({ resultValue: 50, specificationMin: null, specificationMax: 100 })).toBe('pass');
    expect(status({ resultValue: 120, specificationMin: null, specificationMax: 100 })).toBe(
      'fail',
    );
    expect(status({ resultValue: 98, specificationMin: null, specificationMax: null })).toBe(
      'unknown',
    );
  });

  it('passes through canVerify and derives needsVerification from status', () => {
    expect(buildVerificationViewData(verificationViewSource(), { canVerify: true }).canVerify).toBe(
      true,
    );
    expect(
      buildVerificationViewData(verificationViewSource({ status: 'entered' }), { canVerify: false })
        .needsVerification,
    ).toBe(true);
    expect(
      buildVerificationViewData(verificationViewSource({ status: 'verified' }), {
        canVerify: false,
      }).needsVerification,
    ).toBe(false);
  });

  it('maps the certificate document with an isPdf flag', () => {
    const noDoc = buildVerificationViewData(verificationViewSource(), { canVerify: false });
    expect(noDoc.document).toBeNull();

    const uploadedAt = new Date('2026-05-14T02:00:00.000Z');
    const pdf = buildVerificationViewData(
      verificationViewSource({
        certificateDoc: {
          id: 'doc-1',
          filename: 'cert.pdf',
          fileUrl: 'https://files/cert.pdf',
          mimeType: 'application/pdf',
          uploadedAt,
        },
      }),
      { canVerify: false },
    );
    expect(pdf.document).toEqual({
      id: 'doc-1',
      filename: 'cert.pdf',
      fileUrl: 'https://files/cert.pdf',
      mimeType: 'application/pdf',
      uploadedAt,
      isPdf: true,
    });

    const png = buildVerificationViewData(
      verificationViewSource({
        certificateDoc: {
          id: 'doc-2',
          filename: 'cert.png',
          fileUrl: 'https://files/cert.png',
          mimeType: 'image/png',
          uploadedAt,
        },
      }),
      { canVerify: false },
    );
    expect(png.document?.isPdf).toBe(false);
  });

  it('resolves the standard specification reference by normalized test type', () => {
    expect(
      buildVerificationViewData(verificationViewSource({ testType: 'compaction' }), {
        canVerify: false,
      }).specification.standardReference,
    ).toBe('TMR MRTS04 / AS 1289.5.4.1');
    // "Compaction Test" normalizes to "compaction_test", which is not a known key
    expect(
      buildVerificationViewData(verificationViewSource({ testType: 'Compaction Test' }), {
        canVerify: false,
      }).specification.standardReference,
    ).toBeNull();
  });

  it('returns an empty confidence summary when the result is not AI-extracted', () => {
    expect(
      buildVerificationViewData(verificationViewSource({ aiExtracted: false }), {
        canVerify: false,
      }).confidenceHighlights,
    ).toEqual({ hasLowConfidence: false, lowConfidenceFields: [], fieldStatus: {} });
  });

  it('buckets AI confidence into high / medium / low and flags low fields for review', () => {
    const result = buildVerificationViewData(
      verificationViewSource({
        aiExtracted: true,
        aiConfidence: JSON.stringify({ testType: 0.95, sampleDate: 0.85, resultValue: 0.5 }),
      }),
      { canVerify: false },
    );

    expect(result.confidenceHighlights).toEqual({
      hasLowConfidence: true,
      lowConfidenceFields: ['resultValue'],
      fieldStatus: {
        testType: { confidence: 0.95, status: 'high', needsReview: false },
        sampleDate: { confidence: 0.85, status: 'medium', needsReview: false },
        resultValue: { confidence: 0.5, status: 'low', needsReview: true },
      },
      thresholds: { low: 0.8, medium: 0.9 },
      reviewMessage:
        '1 field(s) have low AI confidence and require manual verification: resultValue',
    });
  });

  it('parses aiConfidence into extractedData when present', () => {
    const result = buildVerificationViewData(
      verificationViewSource({
        aiExtracted: true,
        aiConfidence: JSON.stringify({ testType: 0.95 }),
      }),
      { canVerify: false },
    );
    expect(result.extractedData.aiExtracted).toBe(true);
    expect(result.extractedData.aiConfidence).toEqual({ testType: 0.95 });
  });
});

describe('test-result presentation response wrappers', () => {
  it('wraps test request form metadata under the existing response key', () => {
    const metadata = buildTestRequestFormMetadata(requestFormSource());

    expect(buildTestRequestFormResponse(metadata)).toEqual({ testRequestForm: metadata });
  });

  it('wraps verification view data under the existing response key', () => {
    const verificationView = buildVerificationViewData(verificationViewSource(), {
      canVerify: true,
    });

    expect(buildVerificationViewResponse(verificationView)).toEqual({ verificationView });
  });
});
